In [1]:
import pandas as pd
import numpy as np
train_data = pd.read_csv("used_car_train_20200313.csv",sep=" ")
test_data=pd.read_csv("used_car_testB_20200421.csv",sep=' ')

In [2]:
train_data

,SaleID,name,regDate,model,brand,bodyType,fuelType,gearbox,power,kilometer,...,v_5,v_6,v_7,v_8,v_9,v_10,v_11,v_12,v_13,v_14
0,0,736,20040402,30.0,6,1.0,0.0,0.0,60,12.5,...,0.235676,0.101988,0.129549,0.022816,0.097462,-2.881803,2.804097,-2.420821,0.795292,0.914762
1,1,2262,20030301,40.0,1,2.0,0.0,0.0,0,15.0,...,0.264777,0.121004,0.135731,0.026597,0.020582,-4.900482,2.096338,-1.030483,-1.722674,0.245522
2,2,14874,20040403,115.0,15,1.0,0.0,0.0,163,12.5,...,0.251410,0.114912,0.165147,0.062173,0.027075,-4.846749,1.803559,1.565330,-0.832687,-0.229963
3,3,71865,19960908,109.0,10,0.0,0.0,1.0,193,15.0,...,0.274293,0.110300,0.121964,0.033395,0.000000,-4.509599,1.285940,-0.501868,-2.438353,-0.478699
4,4,111080,20120103,110.0,5,1.0,0.0,0.0,68,5.0,...,0.228036,0.073205,0.091880,0.078819,0.121534,-1.896240,0.910783,0.931110,2.834518,1.923482
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,149995,163978,20000607,121.0,10,4.0,0.0,1.0,163,15.0,...,0.280264,0.000310,0.048441,0.071158,0.019174,1.988114,-2.983973,0.589167,-1.304370,-0.302592
149996,149996,184535,20091102,116.0,11,0.0,0.0,0.0,125,10.0,...,0.253217,0.000777,0.084079,0.099681,0.079371,1.839166,-2.774615,2.553994,0.924196,-0.272160
149997,149997,147587,20101003,60.0,11,1.0,1.0,0.0,90,6.0,...,0.233353,0.000705,0.118872,0.100118,0.097914,2.439812,-1.630677,2.290197,1.891922,0.414931
149998,149998,45907,20060312,34.0,10,3.0,1.0,0.0,156,15.0,...,0.256369,0.000252,0.081479,0.083558,0.081498,2.075380,-2.633719,1.414937,0.431981,-1.659014
149999,149999,177672,19990204,19.0,28,6.0,0.0,1.0,193,12.5,...,0.284475,0.000000,0.040072,0.062543,0.025819,1.978453,-3.179913,0.031724,-1.483350,-0.342674

In [3]:
test_data

,SaleID,name,regDate,model,brand,bodyType,fuelType,gearbox,power,kilometer,...,v_5,v_6,v_7,v_8,v_9,v_10,v_11,v_12,v_13,v_14
0,200000,133777,20000501,67.0,0,1.0,0.0,0.0,101,15.0,...,0.236520,0.000241,0.105319,0.046233,0.094522,3.619512,-0.280607,-2.019761,0.978828,0.803322
1,200001,61206,19950211,19.0,6,2.0,0.0,0.0,73,6.0,...,0.261518,0.000000,0.120323,0.046784,0.035385,2.997376,-1.406705,-1.020884,-1.349990,-0.200542
2,200002,67829,20090606,5.0,5,4.0,0.0,0.0,120,5.0,...,0.261691,0.090836,0.000000,0.079655,0.073586,-3.951084,-0.433467,0.918964,1.634604,1.027173
3,200003,8892,20020601,22.0,9,1.0,0.0,0.0,58,15.0,...,0.236050,0.101777,0.098950,0.026830,0.096614,-2.846788,2.800267,-2.524610,1.076819,0.461610
4,200004,76998,20030301,46.0,6,0.0,NaN,0.0,116,15.0,...,0.257000,0.000000,0.066732,0.057771,0.068852,2.839010,-1.659801,-0.924142,0.199423,0.451014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,249995,111443,20041005,4.0,4,0.0,NaN,1.0,150,15.0,...,0.263668,0.000292,0.141804,0.076393,0.039272,2.072901,-2.531869,1.716978,-1.063437,0.326587
49996,249996,152834,20130409,65.0,1,0.0,0.0,0.0,179,4.0,...,0.255310,0.000991,0.155868,0.108425,0.067841,1.358504,-3.290295,4.269809,0.140524,0.556221
49997,249997,132531,20041211,4.0,4,0.0,0.0,1.0,147,12.5,...,0.262933,0.000318,0.141872,0.071968,0.042966,2.165658,-2.417885,1.370612,-1.073133,0.270602
49998,249998,143405,20020702,40.0,1,4.0,0.0,1.0,176,15.0,...,0.282106,0.000023,0.067483,0.067526,0.009006,2.030114,-2.939244,0.569078,-1.718245,0.316379
49999,249999,78202,20090708,32.0,8,1.0,0.0,0.0,0,3.0,...,0.231449,0.103947,0.096027,0.062328,0.110180,-3.689090,2.032376,0.109157,2.202828,0.847469

In [4]:
test_data['notRepairedDamage'].replace('-','0.0',inplace=True)
test_data['notRepairedDamage']=test_data['notRepairedDamage'].astype('float64')

In [5]:
train_data['notRepairedDamage'].replace('-','0.0',inplace=True)
train_data['notRepairedDamage']=train_data['notRepairedDamage'].astype('float64')

In [6]:
train_data['notRepairedDamage'].value_counts()

0.0    135685
1.0     14315
Name: notRepairedDamage, dtype: int64

In [7]:
test_data['notRepairedDamage'].value_counts()

0.0    45293
1.0     4707
Name: notRepairedDamage, dtype: int64

In [8]:
train_data=train_data.fillna(train_data.median())
test_data=test_data.fillna(test_data.median())

In [9]:
train_data['power'][train_data['power']>600]=600
train_data['power'].describe()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

count    150000.000000
mean        116.860973
std          70.075256
min           0.000000
25%          75.000000
50%         110.000000
75%         150.000000
max         600.000000
Name: power, dtype: float64

In [10]:
features=train_data.columns.tolist()
features.remove('price')
features.remove('SaleID')
features

['name',
 'regDate',
 'model',
 'brand',
 'bodyType',
 'fuelType',
 'gearbox',
 'power',
 'kilometer',
 'notRepairedDamage',
 'regionCode',
 'seller',
 'offerType',
 'creatDate',
 'v_0',
 'v_1',
 'v_2',
 'v_3',
 'v_4',
 'v_5',
 'v_6',
 'v_7',
 'v_8',
 'v_9',
 'v_10',
 'v_11',
 'v_12',
 'v_13',
 'v_14']

In [11]:
from sklearn.preprocessing import MinMaxScaler
min_max_scalar=MinMaxScaler()
x=min_max_scalar.fit_transform(train_data[features].values)
x_test=min_max_scalar.transform(test_data[features].values)

In [12]:
y=train_data['price']

In [13]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2)

In [14]:
from tensorflow import keras

In [15]:
# 搭建网络模型
model_k=keras.Sequential([
    keras.layers.Dense(250,activation='relu',input_shape=[len(features)]),
    keras.layers.Dense(250,activation='relu'),
    keras.layers.Dense(250,activation='relu'),
    keras.layers.Dense(1)
])

In [20]:
model_k.compile(loss='mean_absolute_error',optimizer='Adam')
model_k.fit(train_x,train_y,batch_size=1024,epochs=40)

Epoch 1/40
118/118 [==============================] - 2s 17ms/step - loss: 541.0606
Epoch 2/40
118/118 [==============================] - 3s 23ms/step - loss: 532.9660
Epoch 3/40
118/118 [==============================] - 2s 14ms/step - loss: 530.3004
Epoch 4/40
118/118 [==============================] - 2s 16ms/step - loss: 528.8658
Epoch 5/40
118/118 [==============================] - 1s 12ms/step - loss: 528.9573
Epoch 6/40
118/118 [==============================] - 3s 23ms/step - loss: 528.9163
Epoch 7/40
118/118 [==============================] - 3s 23ms/step - loss: 528.6832
Epoch 8/40
118/118 [==============================] - 2s 16ms/step - loss: 526.7199
Epoch 9/40
118/118 [==============================] - 3s 21ms/step - loss: 526.0911
Epoch 10/40
118/118 [==============================] - 2s 20ms/step - loss: 524.2471
Epoch 11/40
118/118 [==============================] - 2s 20ms/step - loss: 523.9323
Epoch 12/40
118/118 [==============================] - 2s 15ms/step - loss: 523.8896
Epoch 13/40
118/118 [==============================] - 2s 19ms/step - loss: 524.0610
Epoch 14/40
118/118 [==============================] - 3s 23ms/step - loss: 521.9081
Epoch 15/40
118/118 [==============================] - 2s 14ms/step - loss: 522.0490
Epoch 16/40
118/118 [==============================] - 2s 17ms/step - loss: 523.2331
Epoch 17/40
118/118 [==============================] - 2s 16ms/step - loss: 521.2529
Epoch 18/40
118/118 [==============================] - 2s 16ms/step - loss: 518.8619
Epoch 19/40
118/118 [==============================] - 2s 14ms/step - loss: 518.9584
Epoch 20/40
118/118 [==============================] - 2s 13ms/step - loss: 518.9773
Epoch 21/40
118/118 [==============================] - 1s 12ms/step - loss: 517.4516
Epoch 22/40
118/118 [==============================] - 2s 14ms/step - loss: 518.1902
Epoch 23/40
118/118 [==============================] - 2s 19ms/step - loss: 516.0073
Epoch 24/40
118/118 [==============================] - 2s 14ms/step - loss: 516.1388
Epoch 25/40
118/118 [==============================] - 2s 16ms/step - loss: 515.5238
Epoch 26/40
118/118 [==============================] - 2s 15ms/step - loss: 518.8126
Epoch 27/40
118/118 [==============================] - 2s 18ms/step - loss: 514.6334
Epoch 28/40
118/118 [==============================] - 2s 16ms/step - loss: 513.7528
Epoch 29/40
118/118 [==============================] - 2s 13ms/step - loss: 512.2773
Epoch 30/40
118/118 [==============================] - 1s 12ms/step - loss: 513.2963
Epoch 31/40
118/118 [==============================] - 2s 14ms/step - loss: 515.6002
Epoch 32/40
118/118 [==============================] - 2s 19ms/step - loss: 513.0410
Epoch 33/40
118/118 [==============================] - 4s 30ms/step - loss: 512.4632
Epoch 34/40
118/118 [==============================] - 3s 27ms/step - loss: 510.3594
Epoch 35/40
118/118 [==============================] - 2s 20ms/step - loss: 514.6906
Epoch 36/40
118/118 [==============================] - 1s 11ms/step - loss: 509.1786
Epoch 37/40
118/118 [==============================] - 3s 22ms/step - loss: 512.0118
Epoch 38/40
118/118 [==============================] - 4s 30ms/step - loss: 509.2451
Epoch 39/40
118/118 [==============================] - 3s 25ms/step - loss: 507.0288
Epoch 40/40
118/118 [==============================] - 4s 32ms/step - loss: 508.3309

In [17]:
from sklearn.metrics import mean_absolute_error

In [21]:
print('训练集的MEA',mean_absolute_error(train_y,model_k.predict(train_x)))
print('验证集的MEA',mean_absolute_error(test_y,model_k.predict(test_x)))

训练集的MEA 509.0887481609002
验证集的MEA 526.8595625188192

In [22]:
# 搭建网络模型
model=keras.Sequential([
    keras.layers.Dense(250,activation='relu',input_shape=[len(features)]),
    keras.layers.Dense(250,activation='relu'),
    keras.layers.Dense(250,activation='relu'),
    keras.layers.Dense(1)
])
model.compile(loss='mean_absolute_error',optimizer='Adam')
model.fit(x,y,batch_size=1024,epochs=40)

Epoch 1/40
147/147 [==============================] - 2s 12ms/step - loss: 4696.6904
Epoch 2/40
147/147 [==============================] - 3s 24ms/step - loss: 1987.6040
Epoch 3/40
147/147 [==============================] - 4s 26ms/step - loss: 1116.5126
Epoch 4/40
147/147 [==============================] - 2s 17ms/step - loss: 995.6006
Epoch 5/40
147/147 [==============================] - 2s 16ms/step - loss: 922.4272
Epoch 6/40
147/147 [==============================] - 3s 22ms/step - loss: 870.5872
Epoch 7/40
147/147 [==============================] - 2s 16ms/step - loss: 829.6621
Epoch 8/40
147/147 [==============================] - 2s 15ms/step - loss: 795.5463
Epoch 9/40
147/147 [==============================] - 3s 19ms/step - loss: 767.6291
Epoch 10/40
147/147 [==============================] - 3s 21ms/step - loss: 742.0792
Epoch 11/40
147/147 [==============================] - 3s 20ms/step - loss: 720.7732
Epoch 12/40
147/147 [==============================] - 4s 24ms/step - loss: 702.7720
Epoch 13/40
147/147 [==============================] - 4s 26ms/step - loss: 686.6672
Epoch 14/40
147/147 [==============================] - 3s 22ms/step - loss: 672.1102
Epoch 15/40
147/147 [==============================] - 3s 21ms/step - loss: 657.7816
Epoch 16/40
147/147 [==============================] - 3s 22ms/step - loss: 647.8029
Epoch 17/40
147/147 [==============================] - 4s 27ms/step - loss: 634.6553
Epoch 18/40
147/147 [==============================] - 4s 25ms/step - loss: 623.9357
Epoch 19/40
147/147 [==============================] - 4s 25ms/step - loss: 615.9027
Epoch 20/40
147/147 [==============================] - 4s 27ms/step - loss: 607.3221
Epoch 21/40
147/147 [==============================] - 5s 32ms/step - loss: 598.9689
Epoch 22/40
147/147 [==============================] - 5s 32ms/step - loss: 594.3382
Epoch 23/40
147/147 [==============================] - 3s 21ms/step - loss: 590.4839
Epoch 24/40
147/147 [==============================] - 3s 22ms/step - loss: 584.2366
Epoch 25/40
147/147 [==============================] - 3s 21ms/step - loss: 579.3563
Epoch 26/40
147/147 [==============================] - 3s 20ms/step - loss: 575.1325
Epoch 27/40
147/147 [==============================] - 4s 28ms/step - loss: 570.5205
Epoch 28/40
147/147 [==============================] - 3s 24ms/step - loss: 567.1704
Epoch 29/40
147/147 [==============================] - 5s 32ms/step - loss: 565.7838
Epoch 30/40
147/147 [==============================] - 5s 34ms/step - loss: 564.3921
Epoch 31/40
147/147 [==============================] - 3s 20ms/step - loss: 557.8003
Epoch 32/40
147/147 [==============================] - 3s 19ms/step - loss: 555.1509
Epoch 33/40
147/147 [==============================] - 3s 19ms/step - loss: 553.0866
Epoch 34/40
147/147 [==============================] - 3s 23ms/step - loss: 551.6583
Epoch 35/40
147/147 [==============================] - 3s 23ms/step - loss: 547.4223
Epoch 36/40
147/147 [==============================] - 3s 22ms/step - loss: 545.5762
Epoch 37/40
147/147 [==============================] - 3s 23ms/step - loss: 542.5033
Epoch 38/40
147/147 [==============================] - 4s 28ms/step - loss: 545.0734
Epoch 39/40
147/147 [==============================] - 4s 30ms/step - loss: 540.1848
Epoch 40/40
147/147 [==============================] - 4s 27ms/step - loss: 536.5410

In [25]:
predict_y=model.predict(x_test)
result=pd.DataFrame()
result['SaleID']=test_data['SaleID']
result['price']=predict_y
result['price'][result['price']<11]=11
result.to_csv('./ans_nn.csv',index=False)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [26]:
result[result['price']<11]

Empty DataFrame
Columns: [SaleID, price]
Index: []

In [27]:
def show_stats(data):
    print('max:',np.max(data))
    print('min:',np.min(data))
    print('ptp:',np.ptp(data))
    print('men:',np.mean(data))
    print('std:',np.std(data))
    print('var:',np.var(data))

In [28]:
show_stats(predict_y)

max: 1968042.1
min: -291.28552
ptp: 1968333.4
men: 6080.563
std: 19391.123
var: 376015650.0